import { TypeProjectDto } from "./TypeProject.dto";

export interface RequestInvertionDto {
    PROY_CODIGO: string;
    PROY_NOMBRE: string;
    PROY_TIPO: TypeProjectDto[];
    PROY_DEPENDENCIA_RESPONSABLE: string;
    PROY_DEPENDENCIA_FUNCIONAL_RESPONSABLE: ["PROY_DEPENDENCIA_FUNCIONAL_RESPONSABLE8", "PROY_DEPENDENCIA_FUNCIONAL_RESPONSABLE5", "PROY_DEPENDENCIA_FUNCIONAL_RESPONSABLE6"];
    PROY_ENTIDAD_NACIONAL_INVOLUCRADA: ["PROY_ENTIDAD_NACIONAL_INVOLUCRADA8", "PROY_ENTIDAD_NACIONAL_INVOLUCRADA5", "PROY_ENTIDAD_NACIONAL_INVOLUCRADA6"];
    PROY_DEPENDENCIAS_INVOLUCRADAS: ["PROY_DEPENDENCIAS_INVOLUCRADAS8", "PROY_DEPENDENCIAS_INVOLUCRADAS5", "PROY_DEPENDENCIAS_INVOLUCRADAS6"];
    PROY_COBERTURA: ["PROY_COBERTURA8", "PROY_COBERTURA5", "PROY_COBERTURA6"];
    PROY_JUSTIFICACION_ANTECEDENTES: "pueba3_PROY_JUSTIFICACION_ANTECEDENTES";
    PROY_POBLACION_AFECTADA: "pueba3_PROY_POBLACION_AFECTADA";
    PROY_POBLACION_OBJETO: "pueba3_PROY_POBLACION_OBJETO";
    PROY_CARACTERISTICAS_DEMOGRAFICAS: "pueba3_PROY_CARACTERISTICAS_DEMOGRAFICAS";
    PROY_ANALISIS_PARTICIPANTES: ["PROY_ANALISIS_PARTICIPANTES8", "PROY_ANALISIS_PARTICIPANTES5", "PROY_ANALISIS_PARTICIPANTES6"];
    PROY_OBJETIVO_GENERAL: "pueba3_PROY_OBJETIVO_GENERAL";
    PROY_DESCRIPCION_GENERAL: "pueba3_PROY_DESCRIPCION_GENERAL";
    PROY_INDICADOR_GENERAL: "pueba3_PROY_INDICADOR_GENERAL";
    PROY_LINEA_BASE_GENERAL: "pueba3_PROY_LINEA_BASE_GENERAL";
    PROY_META_GENERAL: "pueba3_PROY_META_GENERAL";
    PROY_MES_INICIO_GENERAL: "2023-08-03T12:34:56.789Z";
    PROY_MES_FINAL_GENERAL: "2023-09-10T12:10:33.789Z";
    PROY_ENTREGABLE_GENERAL: "pueba3_PROY_ENTREGABLE_GENERAL";
    PROY_DESCRIPCION_ENTREGABLE_GENERAL: "pueba3_PROY_DESCRIPCION_ENTREGABLE_GENERAL";
    PROY_OBJETIVO_ESPECIFICO: ["PROY_OBJETIVO_ESPECIFICO8", "PROY_OBJETIVO_ESPECIFICO5", "PROY_OBJETIVO_ESPECIFICO6"];
    PROY_ACTIVIDADES: ["PROY_ACTIVIDADES8", "PROY_ACTIVIDADES5", "PROY_ACTIVIDADES6"]
}